#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

### Config

bspc monitor -d           

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_struts    true
bspc config top_padding           12
bspc config single_monocle        true

### Colors

bspc config normal_border_color "#ccdee1"
bspc config active_border_color "#e2eaeb"
bspc config focused_border_color "#7e97a0"
bspc config presel_feedback_color "#ccdee1"

### Autostart

# Xinput
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# Xkbmap
setxkbmap es -option ctrl:nocaps

# Feh
feh --bg-fill ~/Images/Wallpapers/0316.png

# Polybar
polybar -r bar
